libusb: Require at least libusb-1.0 version 1.0.9.
This fixes the following build error (see issue #76):

  /usr/local/lib/libuhd.so: undefined reference to `libusb_error_name'

The libusb_error_name() API call was added in 1.0.9.